### ISSUE TITLE
Distribution of pem files and volume

### ISSUE THREAD

**Issue by rahulsahay19** [robrich/https-aspnet-core-docker-deep-dive#4]
Hi,

Facing one issue while distributing this. Let's say, set of developers are going to use this image from some repo let's say docker hub. On their machine, they installed mkcert and installed the cert at root location. Now, they take the pem files and copied at the same place, where they have kept the compose file. But, while running on another machine, looks like this pem file can't get copied into container and at the same time, volume mapping gets screwed. here is the sample compose file

```
version: '3.4'

networks:
    default:
        external:
            name: pnext-network

services:
  identityprovider:
    image: ${DOCKER_REGISTRY}rahulsahay19/pnext-idp:dev
    #uncomment this if you are developing locally and building for the first time
    # build:
    #   context: .
    #   dockerfile: kognifai.IdentityProvider/Dockerfile
    container_name: identityprovider
    external_links: ["entitlementsapi"]
```

Override

```
version: '3.4'

services:
  identityprovider:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTPS_PORT=9445
                 
    ports:
      - "9002:9002"
      - "9445:9445"      
    volumes:
      - "./kognifai.IdentityProvider/db:/app/db"
      - "./kognifai.IdentityProvider/logs:/app/logs"
```

and docker file. Although, here i am referring image as docker file can't be supplied to different ppl.

```
FROM golang:alpine as cert

RUN apk update \
    && apk add git openssl nss-tools \
    && rm -rf /var/cache/apk/*

RUN cd /go && \
    go get -u github.com/FiloSottile/mkcert && \
    cd src/github.com/FiloSottile/mkcert && \
    go build -o /bin/mkcert

WORKDIR /root/.local/share/mkcert
# copied from %localappdata%\mkcert

# Rather pick up cert files from the current directory where image is located. 
COPY ./rootCA*.pem /root/.local/share/mkcert/
# COPY ./kognifai.IdentityProvider/rootCA*.pem /root/.local/share/mkcert/


# make a pfx with known password by making a pem/key then converting it
# includes minikube and docker ips
RUN mkcert -install \
    && mkcert -key-file docker-dev.key -cert-file docker-dev.pem dockernat 10.0.75.1 localhost 127.0.0.1 identityprovider \
    && openssl pkcs12 -export -out docker-dev.pfx -inkey docker-dev.key -in docker-dev.pem -certfile rootCA.pem -passout pass:poseidon


FROM mcr.microsoft.com/dotnet/core/sdk:2.2-alpine as base

WORKDIR /src

COPY ["kognifai.IdentityProvider/kognifai.IdentityProvider.csproj", "kognifai.IdentityProvider/"]
COPY ["kognifai.IdentityProvider/NuGet.config", "kognifai.IdentityProvider/"]
COPY ["kognifai.Entitlements.API.Client/kognifai.Entitlements.API.Client.csproj", "kognifai.Entitlements.API.Client/"]
RUN dotnet restore "kognifai.IdentityProvider/kognifai.IdentityProvider.csproj"
COPY . ./
WORKDIR /src/kognifai.IdentityProvider

RUN dotnet publish "kognifai.IdentityProvider.csproj" -c Debug -o /dist

FROM mcr.microsoft.com/dotnet/core/aspnet:2.2-alpine

FROM base AS final

COPY --from=cert /bin/mkcert /bin/mkcert
# root cert but not root private key:
COPY --from=cert /root/.local/share/mkcert/rootCA.pem /root/.local/share/mkcert/rootCA.pem
COPY --from=cert /root/.local/share/mkcert/docker-dev.pfx /app/

# tell ASP.NET Core to use the cert
ENV Kestrel__Certificates__Default__Path=/app/docker-dev.pfx
ENV Kestrel__Certificates__Default__Password=poseidon


# trust root cert
RUN apk update \
    && apk add nss-tools \
    && rm -rf /var/cache/apk/* \
    && mkcert -install \
    && apk del nss-tools \
    && rm -rf /bin/mkcert
    

WORKDIR /app
VOLUME /kognifai.IdentityProvider/db
VOLUME /kognifai.IdentityProvider/logs


COPY --from=base /dist /app
RUN ls
RUN pwd

ENV ASPNETCORE_ENVIRONMENT Development
ENV ASPNETCORE_URLS https://+:9445;http://+:9002
EXPOSE 9002 9445

CMD ["dotnet", "kognifai.IdentityProvider.dll"]
```

![mkcert](https://user-images.githubusercontent.com/3886381/70795105-15d0f500-1dc5-11ea-83db-34598b980ba7.png)

Not sure, whether doing anything wrong before distributing locally. Thanks.
same goes with volume as well, it didn't copied in the folder created. However, on my machine, when I run them with image as well, it works fine.

**Comment by robrich** [comment]
Not sure where volume mapping fell off.  Can you share the console output?

After copying the pem into place in `%localappdata%\mkcert`, have each person run `mkcert -install` to get the root cert installed on their machines too.  That'll likely fix the trust chain.

And if they're using this developer image from a registry, we're almost to the point where you'll want an internal CA that distributes these root certificates via Active Directory rather than copying pem files around. ... almost.

**Comment by rahulsahay19** [comment]
I am guessing the issue is in docker file copy command for PEM file. I am thinking of doing something like this

```
# COPY ./Kognifai.Entitlements.API/rootCA*.pem /root/.local/share/mkcert/
# Rather pick up cert files from the current directory where image is located. 
VOLUME /Kognifai.Entitlements.API/PEM
```
and then run from the docker run command like
docker run --rm -d -p 9002:9002 -p 9445:9445 -e ASPNETCORE_URLS="https://+;http://+" -e ASPNETCORE_HTTPS_PORT=9445 -e ASPNETCORE_ENVIRONMENT=Development -v D:\Pnext-docker\PEM\:/root/.local/share/mkcert/ -v D:\Pnext-docker\IDP\db:/app/db -v D:\Pnext-docker\IDP\logs:/app/logs rahulsahay19/pnext-idp:dev. 

I am guessing that copied file to the cert location remained old one hence trust chain wasn't happening. Let's say, if I change copy with volume then I can map at run time as well, even then i guess docker-compose should work. Not sure, whether thinking on the right line?

**Comment by rahulsahay19** [comment]
Not sure about this. "And if they're using this developer image from a registry, we're almost to the point where you'll want an internal CA that distributes these root certificates via Active Directory rather than copying pem files around. ... almost." because I published the same in dockerhub and i was testing on different machine. And, I guess copy pem file wasn't happening in this case, hence trust chaining was not building. Not sure about this internal CA process via active directory. is there any article or process about this?

**Comment by rahulsahay19** [comment]
Hi,

Manage to solve this cert issue. Basically, what I did is on my machine, the cert which i trusted via mkcert. I took that pem file and copied the same into different development box and then rather installing mkcert -install freshly, I kept my machine pem file. This means my machine pem file which actually trusted the container basically trusted the container on the other machine as well.

In case of volume, I will supply the actual db file with downloads and then map the same directory on the host machine. Then, I believe, that should also work. Your comments actually give me clues to fix. Thanks.

**Comment by robrich** [comment]
Wonderful.  Glad you got it solved.  Do you want to dig more into the volume map issue?  What is the console output on others' machines as they start it up?  I'm guessing it might have something to do with https://docs.docker.com/docker-for-windows/#shared-drives

**Comment by robrich** [comment]
Towards distributing certificates via Active Directory, I googled "active directory push certificate" and landed on https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/deployment/distribute-certificates-to-client-computers-by-using-group-policy which seems ok

**Comment by rahulsahay19** [comment]
For voulme map, I didn't provide actual local.litedb file under mount location. I was under illusion that docker will copy to that location. After providing db files to that location. Everything worked as expected. 

One thing I noticed, since I am on .net core 2.2 version, here my image size is coming around 1.8 gb as sdk size itself is 1.5 gb. But, in normal practice, ppl generally keep base as runtime image rather sdk image and then copy the published outputs to that app location which will have runtime image and hence image size will be around 200 MB more or less. But, when i tried to tweak this, it didn't give any error while running, but app didn't get launched. 

I guess, am doing something wrong with it.

**Comment by rahulsahay19** [comment]
Hi @robrich looks like I forgot to close this. Closing this now. Thanks for the help.
